### ISSUE TITLE
The es6 option doesn't work in demo

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint.github.io#137]
When I enable the `es6` environment at http://eslint.org/demo/, the following basic code:
```js
let x;
```
is still not recognized:
```
1:2 - Unexpected token let (undefined)
```

**Comment by gyandeeps** [comment]
I just tried it. Works for me.

**Comment by mzgol** [comment]
> Did u enable `es6` and then hit `OK` at the bottom to really activate it.

I didn't. IMO having to click "OK" is very unintuitive, most online systems with switches I encounter update the options immediately after checking them. Is there a reason why clicking OK should be required?

**Comment by gyandeeps** [comment]
Since we have a large set of checkboxes where we did put a OK button so that when the user is done making all the choices then he can say OK. Bu that's a separate discussion where we can come up witha better way if possible.

But to your question of its working or not working, we can say it works right?

**Comment by mzgol** [comment]
Yeah, this issue is invalid.
