### ISSUE TITLE
Publish documentation translations

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#161]
We have the opportunity to have Chinese translations for our documentation. Some things we need to figure out:
1. How would we store this documentation in the repo? (Is it a separate repo?)
2. How will people get to it? (cn.ESLint.org? eslint.org/cn?)
3. How can we do this in a way that doesn't negatively affect SEO?

**Comment by ilyavolodin** [comment]
If we are talking specifically about Chinese translation, then as far as I understand, offer implied maintaining a separate repository and a completely separate site. I don't think it would be great idea to merge translations into this repository and use our existing site for it, since we would need to do a release every time translations are updated.

**Comment by nzakas** [comment]
Yes, that's what the offer was, I'm looking at additional options. I want to make sure we are considering all possibilities before diving in.

**Comment by ilyavolodin** [comment]
Well, I think I definitely wouldn't want to keep rule documentation translations in eslint main repository, since it would require release for publishing every time and would in general create a bunch of commits unrelated to the core project.
Keeping it in this repository vs. having a separate repository doesn't seem to make much of a difference, other then, with a separate repository, merges can be done with somebody who actually knows the language, instead of us just guessing. Separate repository implies separate site (unless we create some scripts to copy content from one repository to another, which doesn't seem all that necessary)

**Comment by nzakas** [comment]
I'm not opposed to having a separate repo,, but what would we do about share CSS, images, etc? Manually copy them whenever they changed?

**Comment by ilyavolodin** [comment]
Good point, I'm actually not 100% sure what to do about those. Doesn't Github allow for nested repositories somehow? I though I saw something like that. Could we possibly use that?

**Comment by mysticatea** [comment]
Node.js seems to have repositories for localization: e.g. https://github.com/nodejs?utf8=%E2%9C%93&query=ja

I image that "gensite" script takes localization contents from those repositories.
At the time, the script inserts a note "this translated content might be old" if the localization content is older than original.

**Comment by nzakas** [comment]
Okay, so we can start with a separate repo.

**Comment by molee1905** [comment]
Well, [vuejs](https://github.com/vuejs?utf8=%E2%9C%93&query=org) has the same characteristic, with separated repo and new branches.

It seems the final solution for now.

Actually, in the past three weeks, with the efforts of my teammates, the translation is basically completed without proofreading, and has been published to [a temporary site](http://smocean.github.io/) mixing Chinese and English.

In my plan, after completion of proofreading, the final Chinese version of ESLint will be born in the coming weeks。

So, may it be possible to be published to http://cn.eslint.org or http://eslint.cn ?

**Comment by nzakas** [comment]
Yes, if I setup a repo for cn.ESLint.org, can you use that?

**Comment by nzakas** [comment]
I setup a repo for cn.eslint.org. @molee1905 I've given you permission to push to that repo. Please let me know who else should have permission.

**Comment by molee1905** [comment]
Very thanks. 

Now  the mixed version [eslint-zh](https://github.com/smocean/eslint-zh) forked from [eslint.github.io](https://github.com/eslint/eslint.github.io/) is on [smocean](https://github.com/smocean),  i will move it to the new repo after preliminary proofreading  to eliminate typos, inaccurate or obscure statement in Chinese , and work on the new repo, to let more people take part in.

**Comment by nzakas** [comment]
I've setup cn.eslint.org CNAME, so it's now using the new repo: http://cn.eslint.org/

**Comment by molee1905** [comment]
http://cn.eslint.org/  is available now

**Comment by nzakas** [comment]
Awesome!

**Comment by kaicataldo** [comment]
Closing this since the work for this specific task is done. Further discussion is occurring [here](https://github.com/eslint/eslint/issues/11512).
