### ISSUE TITLE
Huge spike in Algolia docs

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#242]
For some reason, there was a huge spike in our Algolia records today. The only real change was to the Gemfile (https://github.com/eslint/eslint.github.io/commit/bc2d8b490fdfceb1c90fb17963887b2eb0a02e36). As a result, I got an email saying that our account could be suspended.

I have no idea what could have caused such a spike or how to fix it. I reverted the Gemfile change for now, but still don't know if that will help or not.

@pixelastic sorry to bug you again, but do you have any idea?

**Comment by nzakas** [comment]
For reference: 

![algolia](https://cloud.githubusercontent.com/assets/38546/14573895/05ed801c-030d-11e6-9096-969456270055.png)

**Comment by pixelastic** [comment]
Whoo, that's a lot of records!

I'm going to have a look at this.

Also, FYI we released another project recently, named [DocSearch](https://community.algolia.com/docsearch/). It is a crawler of technical documentation, to index results in Algolia to make them searchable. It is the exact same principle than the Jekyll plugin, except that instead of indexing records when building the website, it crawl the public website once a day. I'm mentionning it because you might find it easier to handle that way.

Now, let's see what is going on with your records :)

**Comment by pixelastic** [comment]
Looks like you had a huge spike of records on April 15th (120k+), while your average is 5500. This went over your attributed quota, so you got a warning email. Shortly after that your number of records got down to its usual value.

I still don't know what happened exactly. This might be caused be a large number of build operations being run in parallel (~20 I'd say, given the numbers). Maybe a lot of Travis jobs ran in parallel?

I'll try to find more information in the logs and let you know.

**Comment by ilyavolodin** [comment]
@pixelastic The search output was also broken. We would not get left-side column in the output, and then other then the first item, all the rest of the items would be exactly the same. No idea what might've caused it though, other then the change to Gemfile.

**Comment by pixelastic** [comment]
Couldn'd find anything obvious in the logs. I'll put it on a temporary hiccup (looks like too many jobs were run in parallel on the same index, resulting in corrupted data in the end). I'll keep an eye on the issue on our side.

Sorry for that!

**Comment by ilyavolodin** [comment]
Thanks for looking at this! Appreciate your help. I'll close this issue for now, if we see this again, we'll let you know.
