### ISSUE TITLE
Feat: parsers in the demo

### ISSUE THREAD

**Issue by Narretz** [eslint/eslint.github.io#283]
Would be cool if you could specify the parser in the demo - obviously the website needs to make the parsers available. This would be pretty cool to test stuff in typescript-eslint-parser, babel-eslint etc., especially to compare if a certain bug exists in vanilla eslint or in the parser

**Comment by platinumazure** [comment]
It could be a pain in the rear end to have to maintain extra parser dependencies, track versions, etc. Can this be done in a clever way that doesn't require a lot of maintenance on our end?

**Comment by nzakas** [comment]
It would be cool, but I don't think anyone has the time or desire to build out the demo in such a way where this would be possible. Unless you want to submit a pull request, it's unlikely this will be addressed.

**Comment by kaicataldo** [comment]
Closing this since there hasn't been any discussion in quite a while and progress on the issue has stalled. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. 

Feel free to open a new issue with a proposal to continue this discussion if this is something you would like to continue advocating for.
