### ISSUE TITLE
Clarify what versions of ESLint support the new rule format

### ISSUE THREAD

**Issue by cowchimp** [eslint/eslint.github.io#300]
Hi.

I'm support an ESLint plugin that contains a set of rules.
I read this
http://eslint.org/blog/2016/07/eslint-new-rule-format
https://github.com/eslint/eslint.github.io/blob/master/_posts/2016-07-01-eslint-new-rule-format.md

I'm wondering, assuming I update the format of my rules, what is the minimum version of ESLint that knows how to read this new format?

Can this be clarified in the post?

Am asking because if I upgrade, I'm assuming I might be breaking backward comparability for some users running with older versions of ESLint.

Thanks.

**Comment by not-an-aardvark** [comment]
To answer your question, it looks like support for the new format was introduced in https://github.com/eslint/eslint/commit/84704740dfe3688cd9ec171fac3d38f288427acc, so I think any version of ESLint since v2.0.0 should be able to handle the new format.

ESLint 2.0.0 came out about 5 months before the blog post did, so maybe that's why it wasn't included. However, feel free to make a PR to add the info.

**Comment by nzakas** [comment]
We recommend ESLint version 3.0.0 for the new rules formally, though they will work in 2.13.0 as well.

It would probably be better to add that information directly into the docs rather than the blog post, as I'm assuming most people will be looking for that information in the docs: http://eslint.org/docs/developer-guide/working-with-rules

**Comment by vitorbal** [comment]
@cowchimp would you be willing to send a PR that adds this information to the `docs/developer-guide/working-with-rules` doc as @nzakas mentions above?

**Comment by cowchimp** [comment]
Yep. Sent in a PR. Thanks.
