### ISSUE TITLE
Move and restructure documentation 

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#32]
As mentioned in #31 we should move some of the documentation out of ESLint repository and into this one. I suggest we not only move it, we also restructure some of it. I propose removing "Docs" link on the website all together and then:
* Moving "Architecture" under "Developer Guide".
* Renaming "Configuring" to "Configuration" and making it a top level menu, and then moving "Command Line" under it.
* Moving "Integrations" somewhere... Not sure where, maybe under "Configuration" or "About"?

After the move, the only folders that should be left in ESLint repository are: "Rules", "Developer Guide" and  "Configuring". Everything else should be under this repository. Ideally, I would also move out everything from under "Developer Guide" here, except for "Working with Rules" and "Working with Plugins", but I think that could be done a bit later, as a separate pull request.

How does that sounds?

**Comment by nzakas** [comment]
In my mind, the top level should be:

* User guide
* Developer guide
* Demo
* About

I think everything we have falls under these quite nicely. We can probably debate which bucket is appropriate for a few.

Thoughts?

**Comment by ilyavolodin** [comment]
Sounds good. I'm just a bit worried about removing "Rules" from top level. That's probably why most of the people come to the site. Other then that, I think it would simplify navigation significantly. I might even suggest possibly removing "About" as well, and just putting it's content on the home page (will improve CEO as well:-)

**Comment by nzakas** [comment]
We could always link to the rules landing page from the homepage as well. 

We might need a new homepage design to have room for the content on About. I'm not opposed to that, it's just really hard to get design help.

**Comment by ilyavolodin** [comment]
We can leave "About" in for now, and if/when we get some design help, we can remove it and move content to the home page. Linking rules from home page also works fine. I'll work on pull request for those changes in the near future and then I can create and submit XML Sitemap to google.

**Comment by nzakas** [comment]
Awesome!

**Comment by lo1tuma** [comment]
I would prefer to keep all docs in the eslint repository. 

1. If I have no internet connection (e.g. when I am working in a train), I can still read the markdown files in my local eslint copy (that one from npm, not from git). 
2. Additionally to eslint/eslint#993 I think it would be a nice feature to have all documentation available as a man page.

**Comment by nzakas** [comment]
I understand the desire. The problem is that it's really starting to become impractical to keep all documentation in the code repo. I wanted documentation *related to code* to be kept in the eslint repo, but we ended up sticking everything in there out of convenience. That meant important documentation changes always had to wait for another release.

We will be keeping the rules documentation and configuration documentation in the eslint repo, as those are directly related to the code. The man-page request was specifically for rules, and since rule documentation will still be in the eslint repo, we can still do that if someone wants to take it on.

We're at a point now where we need to be able to make changes to the site regardless of release cycle, so I think it makes sense to move as much as we can out of the eslint repo and into this one.

**Comment by lo1tuma** [comment]
> I wanted documentation related to code to be kept in the eslint repo

Why do you think so? I think the documentation should be delivered with the project. The website is just one frontend which displays the documentation.

> That meant important documentation changes always had to wait for another release.

Yes!! A bug in the documentation is also a bug in eslint and it SHOULD be fixed with a patch release.

> The man-page request was specifically for rules

Exactly. As I sad it would be nice to have ALL the documentation of eslint available as a man page (I should create an issue for this feature request).

> We're at a point now where we need to be able to make changes to the site regardless of release cycle, so I think it makes sense to move as much as we can out of the eslint repo and into this one.

I think we should distinguish between the eslint website and the documentation. I agree that we should be able to make changes to the website without making changes to the eslint repo. But I disagree that the documation is just a part of the website, it actually is a part of eslint.
Changes to the website (e.g. the eslint demo) don't require a modification to the eslint repo or a new release of eslint?

**Comment by ilyavolodin** [comment]
I completely disagree with your position. Majority of the large projects on Github don't keep their documentation in the repo. jQuery, Esprima, Grunt, D3 have their documentation on the website, but not mixed with their code. There are multiple reasons for that:

Only a very small percentage of people will clone main repository, 99% will just install it through NPM and read documentation on the web.

A lot of documentation has nothing to do with source code. Why does changing governance model should require a patch release? Or contribution guidelines? How do those relate to the ESLint codebase? Doing patch releases on daily bases to tweak documentation will only annoy consumers.

Markdown is a great format for quick and dirty documentation, but it's very limited for web. I would love to have anchors all over contribution guidelines, so I could link people to specific section of the documentation. Or have affix menu inside of it, because it's so long.

All of the things that do have any relationship to the codebase (api docs, rules, guides for working creating rules and plugins) were left in the main repository, so things that you would actually want to look-up while you are on the train without the internet are still going to be there.

**Comment by nzakas** [comment]
> I think we should distinguish between the eslint website and the documentation. I agree that we should be able to make changes to the website without making changes to the eslint repo. But I disagree that the documation is just only a part of the website, it actually is a part of eslint.

@lo1tuma I think we are actually saying same the thing: There is a distinction between website content and eslint documentation. We may be using different words, but fundamentally we are in agreement. 

The eslint documentation will remain in the ESLint repo. What we are doing is pulling out the website content so we can manage that separately. We want a relationship where the ESLint documentation is a *part* of the website.

> Changes to the website (e.g. the eslint demo) don't require a modification to the eslint repo or a new release of eslint?

There are only a few places where this is true: the homepage, the demo, and the CLA. Everything else is generated from the repo. That also means of there's a problem on one of the other pages, we need to update in two places or else re-run the generate site script (which may pull in additional changes that aren't ready to be published).

Ultimately we need the website to grow into tutorials and more content, and we can't keep adding that into the ESLint repo and be bound by the release schedule.

As I mentioned, I believe all the content you are concerned about will still be in the ESLint repo. And this also doesn't have to be forever. If it turns out splitting the content is a problem, we can always reverse course and fix it. What we can't do right now, however, is keep doing what we're doing blindly. We need to make some significant changes to the site, so it makes sense to try a fresh approach.
