### ISSUE TITLE
Can we show auto-fix results in the demo?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint.github.io#322]
Now that the demo has been rewritten, it would be awesome if we could show auto-fix results! (The motivation for this is to provide a quick way to verify incoming bugs that focus on auto-fix issues.)

It would be awesome if we could show auto-fix results without clobbering the original code, too (or at least allow the user to show fixed/broken code via a toggle maybe?).

Possible tasks (may be inaccurate):

* Ensure source-code-fixer, rule-fixer, etc. are included in the browserify'd ESLint so the web demo can access those modules (might require creating a WebEngine API as noted in other discussions?)
* Ensure fix:true is passed to the linting call so fix info and output are available
* Add control to demo for showing fixed output

**Comment by ilyavolodin** [comment]
I looked into it while rewriting the demo. As you mentioned, it's not something we can do without changes to the core, since `CLIEngine` is not browserified (nor should it). I think approach with WebEngine API is incorrect. We would need to add WebEngine API into the core, and that doesn't make much sense to me, since we specifically telling our customers that the only platform that we support is Node.
I think the more correct approach would be to split auto-fix API into two parts, fixing and saving to a file. Saving to a file part should stay in `CLIEngine`, but fixing should be moved into `linter` object. I'm still not 100% sure why @nzakas put auto-fixing into `CLIEngine`.

**Comment by nzakas** [comment]
Only writing to a file is in CLIEngine. The main functionality is in SourceCodeFixer.

**Comment by ilyavolodin** [comment]
Ah, you are correct. In that case, we should expose `SourceCodeFixer` in the `linter` object (if it's not already exposed. But I don't think it is).

**Comment by not-an-aardvark** [comment]
The functionality for applying a single round of fixes is in SourceCodeFixer, but the multipass logic is in CLIEngine ([here](https://github.com/eslint/eslint/blob/8571ab82af1d86bf4aa6a9be79ece42493607c69/lib/cli-engine.js#L123-L194)). As far as the demo is concerned, it would be nice to be able to look at multipass autofix results, since the intermediate autofix steps aren't really relevant to the user most of the time.

**Comment by nzakas** [comment]
I don't think we should be tacking things onto linter just to expose them to the demo. Id much rather go the WebEngine route and do this is an organized way.

**Comment by gyandeeps** [comment]
I will work on this once https://github.com/eslint/eslint/pull/8631 is merged.

**Comment by gyandeeps** [comment]
WIP - Once 4.1.0 is release then I can update the demo site

![image](https://user-images.githubusercontent.com/5554486/27306722-58176fd6-550c-11e7-89b0-90be707b2dfe.png)

**Comment by gyandeeps** [comment]
@eslint/eslint-team any thoughts on the design :point_up:  ?

**Comment by ilyavolodin** [comment]
Why do we need to show fixed code in separate window? Let's just replace original code with fixed (need to add some sort of button to activate fix mode).

**Comment by platinumazure** [comment]
I like the idea of seeing good and bad code side by side, personally.

**Comment by gyandeeps** [comment]
I like side by side also as I maybe testing some rule and interactively trying things. Otherwise its will so annoying to see my code vanish as soon as i stop typing. Its easy to see the changes applied (for context sake).

**Comment by ilyavolodin** [comment]
In that case, current design looks good to me.
