### ISSUE TITLE
too complicated sentence

### ISSUE THREAD

**Issue by zzzgit** [eslint/eslint.github.io#327]
> ESLint resolves a relative path to a base configuration file relative to the configuration file that uses it unless that file is in your home directory or a directory that isn’t an ancestor to the directory in which ESLint is installed (either locally or globally). In those cases, ESLint resolves the relative path to the base file relative to the linted project directory (typically the current working directory).

this is hard to understrand.
the first sentence is very very long for me.

**Comment by zzzgit** [comment]
how to resolve the relative path?
would you give a example in the documentation?

**Comment by platinumazure** [comment]
Yowzer! I agree, that's a mouthful for sure.

It looks like it's talking about what happens when a configuration `"extends"` another configuration using a relative path.

Unfortunately, I'm not familiar with all of the edge cases for configuration cascading/inheritance, so I'm not in a good position to clarify this. But hopefully someone else on the team can help out!

**Comment by kaicataldo** [comment]
Closing this since there hasn't been any discussion in quite a while and progress on the issue has stalled. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. 

Feel free to open a new issue with a proposal to continue this discussion if this is something you would like to continue advocating for.
