### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by noahcollins** [eslint/eslint.github.io#4]
Generate favicons for various platforms. Update template to point to correctly-sixed favicon sources.

**Comment by vitorbal** [comment]
Thanks @noahcollins, for your suggestion. Unfortunately, it has been more than 2 years since this was created without any interest from the team or someone from the community.
I also think our favicon seems fine as it is, so i'm closing this issue.
If anyone disagrees or feels strongly in favor of this change, please feel free to open the issue again.
