### ISSUE TITLE
Add reminder on how to disable a specific rule to rules pages

### ISSUE THREAD

**Issue by tkrugg** [eslint/eslint.github.io#412]
This is, for example, what I'm calling a rule page:  https://eslint.org/docs/rules/no-await-in-loop
I believe a practical addition to rule pages would be a reminder on how to disable the rule. 

Most of the time people reaching this page will look for a way to disable the rule.
If it sounds good enough, I can send a PR.

**Comment by platinumazure** [comment]
I'm interested in the idea of including a quick link to the inline configuration section as a reminder for how to disable rules, automatically generated during site generation. There might be other approaches but I strongly value keeping any added content brief.

@eslint/eslint-team Thoughts?

**Comment by not-an-aardvark** [comment]
For `no-await-in-loop` in particular, it seems like the documentation mentions a config comment already, so I think it would be reasonable to link to the section there (at least as a first step).

**Comment by kaicataldo** [comment]
Closing this since there hasn't been any discussion in quite a while and progress on the issue has stalled. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. 

Feel free to open a new issue with a proposal to continue this discussion if this is something you would like to continue advocating for. Please also remember that you can always create this rule for yourself and distribute it as a plugin.
