### ISSUE TITLE
set master to be protected branch

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint.github.io#468]
Apologies, I didn't notice master was not protected branch -- added a commit https://github.com/eslint/eslint.github.io/commit/1c31728559fda2eeb803977275b96e14a8886bae (⊙ˍ⊙)

I think we better set it protected, to avoid commit by accident.

**Comment by ilyavolodin** [comment]
We do commit to master branch directly once in a while. I'm not opposed to setting it as protected, but it used to be very helpful feature, until we started having 2 people run releases.

**Comment by platinumazure** [comment]
Maybe we could protect master by default, and then unprotect it whenever we need to push to master directly? I think that's a similar strategy to what we do in ESLint itself.

**Comment by not-an-aardvark** [comment]
For what it's worth, I think we have the ESLint repo configured so that repository admins (i.e. TSC members) are allowed to override the setting that PRs are required to push to master. As a result, they can push to master anyway from the command line. This is how ESLint Jenkins creates release commits on master without creating a PR.

Branch protection also disables force-pushing to the branch for everyone, including repository admins.  We've had to temporarily disable this to force-push a few times on ESLint.

**Comment by kaicataldo** [comment]
Is this still an issue?

**Comment by aladdin-add** [comment]
I'm fine to close it, since it didn't occur again for a long time.

**Comment by kaicataldo** [comment]
Sounds good - we can always re-evaluate in the future!
