### ISSUE TITLE
User Guide missing the "extends": "eslint:recommended" check mark for "no-console" rule

### ISSUE THREAD

**Issue by BrandonYeager** [eslint/eslint.github.io#575]
The table in the Rules page of the User Guide is missing the checkbox specifying that the "no-console" rule `"extends": "eslint:recommended"` property (https://eslint.org/docs/rules/).

The documentation page for the rule is correct.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. This is happening because `no-console` is being removed from `eslint:recommended` in v6.0.0, which is currently in prereleases. We have a versioned copy of the rule page at https://eslint.org/docs/6.0.0/rules/no-console, but there isn't a versioned copy of the `/docs/rules` page.

**Comment by BrandonYeager** [comment]
No longer an issue now that v6.0.0 is released
